#!/usr/local/bin/bash

for theme in themes/*.sh
do
  source "$theme"

  mkdir -p "$theme/resources/META-INF"
  ide_substitutions=""
  for name in "${!colors[@]}"; do
    code="${colors[$name]}"
    code=$(echo "$code" | tr '[:lower:]' '[:upper:]')
    ide_substitutions="s/{{$name}}/$code/g; $ide_substitutions"
  done
  ide_substitutions="s/{{theme}}/$theme/g; $ide_substitutions"
  ide_substitutions="s/{{dark}}/$dark/g; $ide_substitutions"

  sed "$ide_substitutions" "tmpl/resources/Theme.theme.json" >"$theme/resources/$theme.theme.json"

  editor_substitutions=""
  for name in "${!colors[@]}"; do
    code="${colors[$name]}"
    code="${code:1}"
    code=$(echo "$code" | tr '[:upper:]' '[:lower:]')
    editor_substitutions="s/{{$name}}/$code/g; $editor_substitutions"
  done
  editor_substitutions="s/{{theme}}/$theme/g; $editor_substitutions"
  editor_substitutions="s/{{dark}}/$dark/g; $editor_substitutions"

  sed "$editor_substitutions" "tmpl/resources/Theme.xml" >"$theme/resources/$theme.xml"

  plugin_xml_substitutions="s/{{theme}}/$theme/g; s/{{description}}/$description/"
  sed "$plugin_xml_substitutions" "tmpl/resources/META-INF/plugin.xml" >"$theme/resources/META-INF/plugin.xml"
done
