#!/usr/local/bin/bash

invert() {
  local color="$1"
  hex="0x${color:1}"
  printf "#%06X" $((0xFFFFFF - "$hex"))
}

for theme in themes/*.sh
do
  source "$theme"

  colors['invertedRed']=$(invert ${colors['red']})
  colors['invertedGreen']=$(invert ${colors['green']})
  colors['invertedBlue']=$(invert ${colors['blue']})
  colors['invertedPurple']=$(invert ${colors['purple']})
  colors['invertedYellow']=$(invert ${colors['yellow']})

  mkdir -p "$theme/resources/META-INF"
  ide_substitutions=""
  for name in "${!colors[@]}"; do
    code="${colors[$name]}"
    code=$(echo "$code" | tr '[:lower:]' '[:upper:]')
    ide_substitutions="s/{{$name}}/$code/g; $ide_substitutions"
  done
  ide_substitutions="s/{{theme}}/$theme/g; $ide_substitutions"
  ide_substitutions="s/{{dark}}/$dark/g; $ide_substitutions"

  sed "$ide_substitutions" "tmpl/resources/Theme.theme.json" >"$theme/resources/$theme.theme.json"

  editor_substitutions=""
  for name in "${!colors[@]}"; do
    code="${colors[$name]}"
    code="${code:1}"
    code=$(echo "$code" | tr '[:upper:]' '[:lower:]')
    editor_substitutions="s/{{$name}}/$code/g; $editor_substitutions"
  done
  editor_substitutions="s/{{theme}}/$theme/g; $editor_substitutions"
  editor_substitutions="s/{{dark}}/$dark/g; $editor_substitutions"

  sed "$editor_substitutions" "tmpl/resources/Theme.xml" >"$theme/resources/$theme.xml"

  plugin_xml_substitutions="s/{{theme}}/$theme/g; s/{{description}}/$description/"
  sed "$plugin_xml_substitutions" "tmpl/resources/META-INF/plugin.xml" >"$theme/resources/META-INF/plugin.xml"
done
